# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/**/*
  errors:
    # Allow a few gradual migrations; tighten others
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    use_build_context_synchronously: warning
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    avoid_print: warning

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Style preferences
    prefer_single_quotes: true
    always_put_control_body_on_new_line: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_late: true
    directives_ordering: true
    sort_pub_dependencies: false
    # Pedantic-ish
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    unnecessary_parenthesis: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    cancel_subscriptions: true
    close_sinks: true
# End of config
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
